/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jicyoaueqcmhymiixxap"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppY3lvYXVlcWNtaHltaWl4eGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODgxNzcsImV4cCI6MjA3MjM2NDE3N30.qlRlBYXu83Cdrtam47P5AxVfex2RigslfD0tdiq9RjY"

